// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs9QbuAuJUXMGFoxlM4ejs6--CZaOfw4Q',
    appId: '1:772757852538:web:59cd20ffc8d899cf3ac6c3',
    messagingSenderId: '772757852538',
    projectId: 'menu-admin-new',
    authDomain: 'menu-admin-new.firebaseapp.com',
    storageBucket: 'menu-admin-new.firebasestorage.app',
    measurementId: 'G-GGBG477DYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM3Y2T65QvWg8KhivUbpV9BTT6QMEI62g',
    appId: '1:772757852538:android:d8b6b203640bedd13ac6c3',
    messagingSenderId: '772757852538',
    projectId: 'menu-admin-new',
    storageBucket: 'menu-admin-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnubsrqXwYiDYPlgDQPoxw6tvYZ-ByQfg',
    appId: '1:772757852538:ios:71c0c66ceae0211e3ac6c3',
    messagingSenderId: '772757852538',
    projectId: 'menu-admin-new',
    storageBucket: 'menu-admin-new.firebasestorage.app',
    iosBundleId: 'com.example.userAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnubsrqXwYiDYPlgDQPoxw6tvYZ-ByQfg',
    appId: '1:772757852538:ios:71c0c66ceae0211e3ac6c3',
    messagingSenderId: '772757852538',
    projectId: 'menu-admin-new',
    storageBucket: 'menu-admin-new.firebasestorage.app',
    iosBundleId: 'com.example.userAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs9QbuAuJUXMGFoxlM4ejs6--CZaOfw4Q',
    appId: '1:772757852538:web:6ca2c83216452a613ac6c3',
    messagingSenderId: '772757852538',
    projectId: 'menu-admin-new',
    authDomain: 'menu-admin-new.firebaseapp.com',
    storageBucket: 'menu-admin-new.firebasestorage.app',
    measurementId: 'G-XV7X2TKS95',
  );
}
